    // File generated by FlutterFire CLI.
    // ignore_for_file: type=lint
    import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
    import 'package:flutter/foundation.dart'
        show defaultTargetPlatform, kIsWeb, TargetPlatform;

    /// Default [FirebaseOptions] for use with your Firebase apps.
    ///
    /// Example:
    /// ```dart
    /// import 'firebase_options.dart';
    /// // ...
    /// await Firebase.initializeApp(
    ///   options: DefaultFirebaseOptions.currentPlatform,
    /// );
    /// ```
    class DefaultFirebaseOptions {
      static FirebaseOptions get currentPlatform {
        if (kIsWeb) {
          return web;
        }
        switch (defaultTargetPlatform) {
          case TargetPlatform.android:
            return android;
          case TargetPlatform.iOS:
            return ios;
          case TargetPlatform.macOS:
            return macos;
          case TargetPlatform.windows:
            return windows;
          case TargetPlatform.linux:
            throw UnsupportedError(
              'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
            );
          default:
            throw UnsupportedError(
              'DefaultFirebaseOptions are not supported for this platform.',
            );
        }
      }

      static const FirebaseOptions web = FirebaseOptions(
        apiKey: 'AIzaSyCFgha1IrPQBXlc0G8wwWnDzhbWV2XM0Uc',
        appId: '1:948370771334:web:4b89e6583066b2dc4bb007',
        messagingSenderId: '948370771334',
        projectId: 'renteasedb',
        authDomain: 'renteasedb.firebaseapp.com',
        storageBucket: 'renteasedb.firebasestorage.app',
        measurementId: 'G-91D9SR7R0B',
      );

      static const FirebaseOptions android = FirebaseOptions(
        apiKey: 'AIzaSyBz8n1axctGdVFO-VPr0wrggYGAYK6-9Ko',
        appId: '1:948370771334:android:e47c291d00fe1edc4bb007',
        messagingSenderId: '948370771334',
        projectId: 'renteasedb',
        storageBucket: 'renteasedb.firebasestorage.app',
      );

      static const FirebaseOptions ios = FirebaseOptions(
        apiKey: 'AIzaSyDSupF8ltDMyUrrQDZFbPB-aqQ92SThyLw',
        appId: '1:948370771334:ios:29f320f1ee0b24d44bb007',
        messagingSenderId: '948370771334',
        projectId: 'renteasedb',
        storageBucket: 'renteasedb.firebasestorage.app',
        iosBundleId: 'com.example.renteaseApp',
      );

      static const FirebaseOptions macos = FirebaseOptions(
        apiKey: 'AIzaSyDSupF8ltDMyUrrQDZFbPB-aqQ92SThyLw',
        appId: '1:948370771334:ios:29f320f1ee0b24d44bb007',
        messagingSenderId: '948370771334',
        projectId: 'renteasedb',
        storageBucket: 'renteasedb.firebasestorage.app',
        iosBundleId: 'com.example.renteaseApp',
      );

      static const FirebaseOptions windows = FirebaseOptions(
        apiKey: 'AIzaSyCFgha1IrPQBXlc0G8wwWnDzhbWV2XM0Uc',
        appId: '1:948370771334:web:178fe30df399734e4bb007',
        messagingSenderId: '948370771334',
        projectId: 'renteasedb',
        authDomain: 'renteasedb.firebaseapp.com',
        storageBucket: 'renteasedb.firebasestorage.app',
        measurementId: 'G-1LJPQ1TMN7',
      );
    }

